# Generated by Django 4.0.5 on 2022-09-22 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_grade_school_subjectclass_student_course_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='course_grade', to='login.grade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='school',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='course_school', to='login.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grade', to='login.grade'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_school', to='login.school'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subject_school', to='login.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjectClass',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subject_subjectClass', to='login.subjectclass'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subjectclass',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectClass_school', to='login.school'),
        ),
    ]
