# Generated by Django 4.1.1 on 2022-09-23 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectclass',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjectClass_grade', to='login.grade'),
        ),
    ]
