# Generated by Django 4.1.1 on 2022-09-23 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_subjectclass_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectclass',
            name='grade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subjectClass_grade', to='login.grade'),
            preserve_default=False,
        ),
    ]
