# Generated by Django 4.1.1 on 2022-09-23 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_subjectclass_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_grade', to='login.grade'),
        ),
        migrations.AddField(
            model_name='subject',
            name='gradeList',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
