# Generated by Django 4.1.1 on 2022-09-23 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_subject_grade_subject_gradelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subject_grade', to='login.grade'),
            preserve_default=False,
        ),
    ]
