# Generated by Django 4.1.1 on 2022-09-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_subject_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='darkModeEnabled',
            field=models.BooleanField(default=False),
        ),
    ]
