# Generated by Django 4.0.5 on 2022-10-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_checkbox_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskType',
            field=models.CharField(choices=[('HA', 'Hausaufgabe'), ('TS', 'Test'), ('KL', 'Klausur (ohne Test)'), ('KT', 'Klausur (mit Test)')], max_length=50),
        ),
    ]
